<template>
  <div class="minimalist-tab-buttons actions d-flex">
    <!-- TODO: Write test -->
    <a
      v-for="(tab, key) in tabs"
      :key="key"
      :class="{
        'active': tab.key === selected.key,
        'top': type === 'top',
        'bottom': type === 'bottom'
      }"
      class="action"
      href="javascript:void(0)"
      @click="handleClick(tab)"
    >
      {{ tab.key | titleCase }}
    </a>
  </div>
</template>

<script>
export default {
  props: {
    reverse: {
      type: Boolean,
      default: false
    },
    type: {
      type: String,
      default: 'top'
    },
    tabs: {
      type: Array,
      default: () => []
    },
    activeTab: {
      type: Object,
      default: () => {}
    }
  },
  data () {
    return {
      selected: {}
    }
  },
  created () {
    this.selected = this.activeTab
  },
  watch: {
    activeTab (newActiveTab) {
      this.selected = newActiveTab
    }
  },
  methods: {
    /**
       * Handle the click generated by the tab and pass its data object
       *
       * @param {Object} tab
       */
    handleClick (tab) {
      this.selected = tab
      this.$emit('click', tab)
    }
  }
}
</script>

<style lang="scss" scoped>
.actions {
  .action {
    margin-bottom: -1px;
    font-size: 0.75rem;
    padding: 0.5rem 1rem;
    transition: all 0.3s ease;
    cursor: pointer;
    color: #222;
    border-right: 1px solid #ddd;

    &:last-child {
      border-right: 1px solid transparent;
    }

    &.active {
      &.top {
        border-top: 1px solid #ddd;

        &:first-child {
          border-left: 1px solid #ddd;
        }
      }

      &.bottom {
        margin-top: -2px;
        border-top: 1px solid transparent !important;
        border-bottom: 1px solid #ddd !important;

        &:first-child {
          border-left: 1px solid #ddd;
        }
      }
    }

    &:hover {
      background: #ddd;
    }

    &.active {
      background: #f9f9f9;

      &:hover {
        background: #ddd;
      }
    }
  }
}
</style>
